apiVersion: v1
kind: Secret
# github
metadata:
  name: gh-wh-secret
  namespace: kargo-demo
stringData:
  secret: my-not-so-secret-token
#
# quay
# metadata:
#   name: quay-wh-secret
#   namespace: kargo-demo
# stringData:
#   secret: my-insecure-secret
# gitlab
# metadata:
#   name: gitlab-wh-secret
#   namespace: kargo-demo
# stringData:
#   secret-token: my-not-so-secret-token
